---
git:
  depth: 1
language: node_js
node_js:
- '6'
- 'node'
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm update -g
before_script:
- npm install -qg bower
- bower install
